[project]
name = "ai-snippet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "openai>=2.8.0",
    "uvicorn[standard]>=0.38.0",
]
